In [79]:
#1. Import NumPy and print its version.
import numpy as np
np.__version__

'2.1.3'

In [104]:
#2. Make an array from the hours logged column.

import pandas as pd

df = pd.read_csv("it_services_tickets_clean.csv")

hours = np.array(df["hours_logged"])
print(hours)

[  nan  1.34  7.   ... 47.    2.     nan]


/tmp/ipykernel_2572/2699640054.py:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("it_services_tickets_clean.csv")


In [105]:
#3. Print the shape, the size and the data type of that array.
print('Shape:', hours.shape)
print('Size:', hours.size)
print('Dtype:', hours.dtype)

Shape: (48123,)
Size: 48123
Dtype: float64


In [100]:
#4. Make an array of the numbers 1 to 50 using arange.
arr1 = np.arange(1, 51)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [101]:
# 5. Make 10 evenly spaced numbers between 0 and 100 using linspace.
lin10 = np.linspace(0, 100, 10)
lin10

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [84]:
#6. Make an array of 10 zeros and an array of 10 ones.
zeros10 = np.zeros(10)
ones10 = np.ones(10)
print(zeros10)
print(ones10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [85]:
#7. Make a 3 by 3 array of random numbers using seed 42.
rng = np.random.default_rng(42)
rand3x3 = rng.random((3, 3))
rand3x3

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [102]:
#8. Make a 2-D array from the hours logged and billing rate columns.
hour_array1 = df[['hours_logged', 'billing_rate_(usd)']].to_numpy()
hour_array1[:5]

array([[  nan, 39.45],
       [ 1.34, 33.15],
       [ 7.  , 48.1 ],
       [34.63, 52.98],
       [12.76,   nan]])

In [103]:
#9. Print how many dimensions that 2-D array has.
hour_array1.ndim

2

In [106]:
#10. Print the first 5 values of the hours array.
hours[:5]

array([  nan,  1.34,  7.  , 34.63, 12.76])

In [89]:
#11. Print the last 5 values of the hours array.
hours[-5:]

array([50.,  4., 47.,  2., nan])

In [90]:
#12. Print every second value from the first 20 values.
hours[:20:2]

array([   nan,   7.  ,  12.76,    nan,   1.66,    nan,  11.63,  28.  ,
         0.59, 253.85])

In [91]:
#13. Reverse the array.
hours[::-1]

array([  nan,  2.  , 47.  , ...,  7.  ,  1.34,   nan])

In [92]:
#14. Find the sum of the hours array.
hours.sum()

np.float64(nan)

In [93]:
#15. Find the mean, the minimum and the maximum of the hours array.
print('Mean:', hours.mean())
print('Min:', hours.min())
print('Max:', hours.max())

Mean: nan
Min: nan
Max: nan


In [94]:
#16. Find the standard deviation.
hours.std()

np.float64(nan)

In [95]:
#17. Find the median.
np.median(hours)

np.float64(nan)

In [109]:
#18. Count how many values are missing in the array.
print(np.isnan(hours).sum())

11870


In [111]:
#19. Find the mean while ignoring the missing values.
np.nanmean(hours)

np.float64(63.16764267784735)

In [113]:
#20. Replace all the missing values with 0.
hours_no_missing = np.nan_to_num(hours, nan=0)
print(hours_no_missing)

[ 0.    1.34  7.   ... 47.    2.    0.  ]


In [115]:
#21. Count how many values are greater than 100.
print(np.sum(hours > 100))

1588


In [117]:
#22. Show only the values that are greater than 100.
hours[hours > 100]

array([ 253.85,  128.  , 1900.66, ...,  562.22,  141.9 ,  137.56])

In [119]:
#23. Show the values that are between 10 and 50.
hours[(hours >= 10) & (hours <= 50)]

array([34.63, 12.76, 15.3 , ..., 25.23, 50.  , 47.  ])

In [121]:
#24. Count how many values are negative.
print(np.sum(hours < 0))

136


In [123]:
#25. Replace all the negative values with 0.
hours = np.where(hours < 0, 0, hours)
(hours < 0).sum()

np.int64(0)

In [125]:
#26. Sort the array from smallest to largest
sorted_hours = np.sort(hours)

print(sorted_hours)


[ 0.  0.  0. ... nan nan nan]


In [128]:
#27. Find the position of the largest value.
print(np.nanargmax(hours))

10041


In [133]:
#28. Find the position of the smallest value.
print(np.nanargmin(hours))

75


In [136]:
#29. Find the 5 largest values.
print(np.sort(hours[~np.isnan(hours)])[-5:])

[8760.   8760.   8760.   9888.01 9888.01]


In [139]:
#30. Round every value to 1 decimal place.
rounded_hours = np.round(hours, 1)

print(rounded_hours)

[ nan  1.3  7.  ... 47.   2.   nan]


In [141]:
#31. Multiply every value by 2.
(hours * 2)[:10]

array([  nan,  2.68, 14.  , 69.26, 25.52, 30.6 ,   nan, 18.  ,  3.32,
         nan])

In [143]:
#32. Add 10 to every value.
hours_plus_10 = hours + 10

print(hours_plus_10)

[  nan 11.34 17.   ... 57.   12.     nan]


In [146]:
#33. Multiply the hours array by the billing rate array.
billing_rate = df["billing_rate_(usd)"].to_numpy()

revenue = hours * billing_rate

print(revenue)

[    nan  44.421 336.7   ...     nan 233.52      nan]


In [148]:
#34. Check whether the two arrays have the same length.
print(len(hours) == len(billing_rate))

True


In [164]:
#35. Use np.where to mark values above 24 as slow and the rest as fast.
speed = np.where(hours > 24, "slow", "fast")

print(speed)

['fast' 'fast' 'fast' ... 'slow' 'fast' 'fast']


In [165]:
#36. Make an array of the unique priority values.
priority = df["priority"].dropna().to_numpy()
unique_priorities = np.unique(priority)
print(unique_priorities)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


In [166]:
#37. Count how many times each unique priority value appears.
values, counts = np.unique(priority, return_counts=True)

print(values)
print(counts)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']
[  95  107 1931 1966 1934 1919   85 1993 2000 1950 2003 1945 1840 1949
 1941 1891 1969 1907 1950 1880    1 1971 1950 2023  125  130 1934 1898
 1988 1909]


In [167]:
#38. Take the first 100 values and reshape them into a 10 by 10 array.
first_100 = hours[:100]

array_10x10 = first_100.reshape(10, 10)

print(array_10x10)

[[        nan 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
          nan 9.00000e+00 1.66000e+00         nan]
 [        nan 1.44000e+00 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01
  5.90000e-01 7.00000e+00 2.53850e+02 4.20000e+00]
 [5.08100e+01 8.01000e+00 6.79400e+01         nan 3.27100e+01         nan
  6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00]
 [1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01         nan 1.30000e+01
  3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00]
 [        nan 3.92000e+00 2.02200e+01 2.41500e+01 8.40000e+01         nan
  2.70000e+01         nan 4.00000e+00 2.76000e+00]
 [1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01 5.00000e+00 1.14100e+01
          nan 1.80000e+01 1.28000e+02 1.54000e+01]
 [1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02         nan
  4.00000e+00         nan 2.00000e+00         nan]
 [2.05100e+01 1.13300e+01 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00
          nan         nan 3.40000e+01 1.49200e+01]


In [168]:
#39. Transpose that 10 by 10 array.
transposed = array_10x10.T

print(transposed)

[[        nan         nan 5.08100e+01 1.80000e+01         nan 1.12600e+01
  1.90066e+03 2.05100e+01 1.91700e+01 1.30000e+01]
 [1.34000e+00 1.44000e+00 8.01000e+00 3.14400e+01 3.92000e+00 2.40000e+01
  4.00000e+00 1.13300e+01 1.78600e+01 1.09100e+01]
 [7.00000e+00 1.16300e+01 6.79400e+01 3.42000e+00 2.02200e+01 5.26000e+00
  3.00000e+00 5.99100e+01 9.21000e+00 8.00000e+00]
 [3.46300e+01 7.23100e+01         nan 2.44600e+01 2.41500e+01 1.40000e+01
  9.00000e+00 1.00000e+00 5.40000e+01 3.81000e+00]
 [1.27600e+01 2.80000e+01 3.27100e+01         nan 8.40000e+01 5.00000e+00
  1.33350e+02 2.29700e+01         nan 3.73680e+02]
 [1.53000e+01 1.01600e+01         nan 1.30000e+01         nan 1.14100e+01
          nan 0.00000e+00 2.00000e+01 1.13800e+01]
 [        nan 5.90000e-01 6.91000e+00 3.00200e+01 2.70000e+01         nan
  4.00000e+00         nan 6.00000e+00 3.36700e+01]
 [9.00000e+00 7.00000e+00 3.08400e+01 1.15100e+01         nan 1.80000e+01
          nan         nan 1.15600e+01 5.80000e-01]


In [169]:
#40. Flatten it back into a 1-D array.
flattened = array_10x10.flatten()

print(flattened)


[        nan 1.34000e+00 7.00000e+00 3.46300e+01 1.27600e+01 1.53000e+01
         nan 9.00000e+00 1.66000e+00         nan         nan 1.44000e+00
 1.16300e+01 7.23100e+01 2.80000e+01 1.01600e+01 5.90000e-01 7.00000e+00
 2.53850e+02 4.20000e+00 5.08100e+01 8.01000e+00 6.79400e+01         nan
 3.27100e+01         nan 6.91000e+00 3.08400e+01 3.51000e+00 4.34000e+00
 1.80000e+01 3.14400e+01 3.42000e+00 2.44600e+01         nan 1.30000e+01
 3.00200e+01 1.15100e+01 6.30200e+01 1.03000e+00         nan 3.92000e+00
 2.02200e+01 2.41500e+01 8.40000e+01         nan 2.70000e+01         nan
 4.00000e+00 2.76000e+00 1.12600e+01 2.40000e+01 5.26000e+00 1.40000e+01
 5.00000e+00 1.14100e+01         nan 1.80000e+01 1.28000e+02 1.54000e+01
 1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02         nan
 4.00000e+00         nan 2.00000e+00         nan 2.05100e+01 1.13300e+01
 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00         nan         nan
 3.40000e+01 1.49200e+01 1.91700e+01 1.78600e+01 9.

In [170]:
#41. Join two arrays together using np.concatenate.
array1 = hours[:10]
array2 = hours[10:20]

joined = np.concatenate((array1, array2))

print(joined)

[   nan   1.34   7.    34.63  12.76  15.3     nan   9.     1.66    nan
    nan   1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]


In [171]:
#42. Split an array into 5 equal parts.
first_100 = hours[:100]

parts = np.array_split(first_100, 5)

for part in parts:
    print(part)

[   nan   1.34   7.    34.63  12.76  15.3     nan   9.     1.66    nan
    nan   1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]
[50.81  8.01 67.94   nan 32.71   nan  6.91 30.84  3.51  4.34 18.   31.44
  3.42 24.46   nan 13.   30.02 11.51 63.02  1.03]
[   nan   3.92  20.22  24.15  84.      nan  27.      nan   4.     2.76
  11.26  24.     5.26  14.     5.    11.41    nan  18.   128.    15.4 ]
[1.90066e+03 4.00000e+00 3.00000e+00 9.00000e+00 1.33350e+02         nan
 4.00000e+00         nan 2.00000e+00         nan 2.05100e+01 1.13300e+01
 5.99100e+01 1.00000e+00 2.29700e+01 0.00000e+00         nan         nan
 3.40000e+01 1.49200e+01]
[ 19.17  17.86   9.21  54.      nan  20.     6.    11.56    nan   5.85
  13.    10.91   8.     3.81 373.68  11.38  33.67   0.58    nan    nan]


In [172]:
#43. Find the 25th, 50th and 75th percentile.
valid_hours = hours[~np.isnan(hours)]

print("25th percentile:", np.percentile(valid_hours, 25))
print("50th percentile:", np.percentile(valid_hours, 50))
print("75th percentile:", np.percentile(valid_hours, 75))

25th percentile: 4.35
50th percentile: 13.1
75th percentile: 29.49


In [173]:
#44. Find the cumulative sum of the first 20 values.
print(np.cumsum(hours[:20]))

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]


In [174]:
#45. Find the difference between each value and the one before it using np.diff.
print(np.diff(hours[:20]))

[    nan    5.66   27.63  -21.87    2.54     nan     nan   -7.34     nan
     nan     nan   10.19   60.68  -44.31  -17.84   -9.57    6.41  246.85
 -249.65]


In [175]:
#46. Keep every value inside the range 0 to 100 using np.clip.
clipped_hours = np.clip(hours, 0, 100)

print(clipped_hours)

[  nan  1.34  7.   ... 47.    2.     nan]


In [177]:
#47. Convert the array to whole numbers.
whole_hours = hours.astype(int)

print(whole_hours)

[-9223372036854775808                    1                    7 ...
                   47                    2 -9223372036854775808]


/tmp/ipykernel_2572/285459371.py:2: RuntimeWarning: invalid value encountered in cast
  whole_hours = hours.astype(int)


In [178]:
#48. Copy the array, change one value in the copy, and show that the original did not change.
hours_copy = hours.copy()

hours_copy[0] = 9999

print("Original:", hours[0])
print("Copy:", hours_copy[0])


Original: nan
Copy: 9999.0


In [180]:
#49. Save the array to a .npy file and load it back.
np.save("hours_array.npy", hours)


In [181]:
#50. Find the total revenue using np.dot on the hours array and the rate array.
billing_rate = df["billing_rate_(usd)"].to_numpy()

total_revenue = np.dot(
    np.nan_to_num(hours, nan=0),
    np.nan_to_num(billing_rate, nan=0)
)

print("Total Revenue:", total_revenue)

Total Revenue: 127427757.53480002
